# Generated by Django 5.1 on 2024-09-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
