# Generated by Django 5.1 on 2024-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHR', '0002_alter_medication_dosage_alter_medication_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='instruction',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
