# Generated by Django 5.1 on 2024-09-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHR', '0003_medication_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='blood_pressure',
        ),
    ]
