# Generated by Django 5.1 on 2024-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHR', '0004_remove_patientrecord_blood_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='chronic_conditions',
            field=models.JSONField(null=True),
        ),
    ]
