# Generated by Django 5.1 on 2024-09-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHR', '0006_alter_patientrecord_chronic_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DPR', to='EHR.doctorrecord')),
            ],
        ),
    ]
