# Generated by Django 5.1 on 2024-09-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHR', '0007_dpr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpr',
            old_name='patient',
            new_name='doc',
        ),
    ]
